namespace: community
name: azure
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  azure.azcollection: '>=0.1.0'
repository: git@github.com:ansible-collection-migration/community.azure.git
documentation: https://github.com/ansible-collection-migration/community.azure/tree/master/docs
homepage: https://github.com/ansible-collection-migration/community.azure
issues: https://github.com/ansible-collection-migration/community.azure/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
